// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int high = 0;
		int low = 0;
		for (int i = 0; i < N; i++) {
			double randomness = Math.random();
			if(randomness>0.5){
				high+=1;
			}
			else{
				low+=1;
			}
		}
	    if(high>low && low!=0){
			System.out.println("> 0.5: "+ high+" times");
			System.out.println("<= 0.5: "+ low+" times");
			System.out.print("Ratio: "+ (double) low/high);
		}
		else if(low>high && high!=0){
			System.out.println("> 0.5: "+ high +" times");
			System.out.println("<= 0.5: "+ low+" times");
			System.out.print("Ratio: "+ (double) high/low);
		}
		else if(low==high){
			System.out.println("> 0.5: "+ high +" times");
			System.out.println("<= 0.5: "+ low+" times");
			System.out.print("Ratio: "+ (double) high/low);
		}
		else{
			System.out.println("> 0.5: "+ high+" times");
			System.out.println("<= 0.5: "+ low+" times");
		}


	}
}
